#version 460
#extension GL_EXT_nonuniform_qualifier : require
layout(local_size_x = 16,local_size_y = 4) in;

#include "structs.glsl"
#include "vk_uniforms.glsl"

layout(std430,set=1,binding=5) readonly buffer LightBuf {
    Light light_v[];
};
layout(std430, set = 2, binding = 3) buffer GBuf {
    GBufferPixel gbuffer[];
};
layout(set = 3, binding = 0, rgba32f) uniform image2D outImage;

void main() {
    ivec2 gid  = ivec2(gl_GlobalInvocationID.xy);
    if (gid.x >= int(width) || gid.y >= int(height)) return;
    uint pidx = uint(gid.y) * width + uint(gid.x);
    // TODO
}