#version 460
#extension GL_EXT_nonuniform_qualifier : require
layout(local_size_x = 8,local_size_y = 8) in;

#include "structs.glsl"
#include "vk_uniforms.glsl"

layout(std430,set=1,binding=3) readonly buffer MatBuf {
    Mat mats[];
};
layout(std430, set = 2, binding = 3) buffer GBuf {
    GBufferPixel gbuffer[];
};
layout(set = 3, binding = 0, rgba32f) uniform image2D outImage;
layout(set = 3, binding = 1, rgba32f) uniform image2D accumImage;
layout(set = 3, binding = 2, rgba32f) uniform image2D reflAccumImage;

void main() {
    ivec2 gid  = ivec2(gl_GlobalInvocationID.xy);
    if (gid.x >= int(width) || gid.y >= int(height)) return;
    uint pidx = uint(gid.y) * width + uint(gid.x);

    vec3 img = imageLoad(outImage,gid).rgb;
    vec3 hist = imageLoad(accumImage,gid).rgb;
    vec3 refl = imageLoad(reflAccumImage,gid).rgb;
    
    vec3 col = img;
    GBufferPixel px = gbuffer[pidx];
    if (px.valid!=-1&& px.matId!=0u){
        Mat mat = mats[px.matId-1];
        vec3 n = normalize(px.norm.xyz);
        vec3 v = normalize(camPos - px.pos.xyz);
        float nDotV = max(dot(n,v),0.0);
        float fresnel = schlick(nDotV,mat.specular.w);
        col += refl*fresnel;
    }

    float a = (framec == 0) ? 1.0 : max(1.0/float(framec+1),0.05);
    vec3 accum = mix(hist,col,a);

    imageStore(accumImage, ivec2(gid), vec4(accum,1.0));
    imageStore(outImage, ivec2(gid), vec4(accum,1.0));
}