#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_EXT_nonuniform_qualifier : require

#include "structs.glsl"
#include "vk_uniforms.glsl"
#include "rt_payload.glsl"

layout(std430,set=1,binding=0) readonly buffer TriBuf {
    Tri tris[];
};
layout(std430,set=1,binding=1) readonly buffer SphrBuf {
    Sphr spheres[];
};
layout(std430,set=1,binding=2) readonly buffer BVHBuf {
    BVH bvh_v[];
};
layout(std430,set=1,binding=3) readonly buffer MatBuf {
    Mat mats[];
};
layout(std430,set=1,binding=4) readonly buffer PrimBuf {
    uint prims[];
};
layout(std430,set=1,binding=5) readonly buffer LightBuf {
    Light light_v[];
};
layout(set = 1, binding = 6) uniform sampler2DArray baseTexArr;
layout(set = 1, binding = 7) uniform sampler2DArray normalTexArr;
layout(set = 1, binding = 8) uniform sampler2DArray specularTexArr;
layout(set = 1, binding = 9) uniform accelerationStructureEXT tlas;

layout(std430, set = 2, binding = 3) buffer GBuf {
    GBufferPixel gbuffer[];
};

layout(set = 3, binding = 2, rgba32f) uniform image2D reflAccumImage;

void main() {
    ivec2 gid  = ivec2(gl_GlobalInvocationID.xy);
    if (gid.x >= int(width) || gid.y >= int(height)) return;
    uint pidx = uint(gid.y) * width + uint(gid.x);
    // TODO
}